PACKAGE := ddccontrol-db
VERSION := $(shell sed -n '1p' VERSION)

PREFIX ?= /usr/local
DATADIR ?= $(PREFIX)/share
LOCALEDIR ?= $(DATADIR)/locale
DBDIR ?= $(DATADIR)/ddccontrol-db
DESTDIR ?=

-include config.mk

INSTALL ?= install
INSTALL_DATA ?= $(INSTALL) -m 644
MKDIR_P ?= mkdir -p
MSGFMT ?= msgfmt
XGETTEXT ?= xgettext
MSGMERGE ?= msgmerge
PERL ?= perl
DDCCONTROL ?= ddccontrol

AVAILABLE_LANGUAGES := $(shell sed -e '/^[[:space:]]*\#/d' -e '/^[[:space:]]*$$/d' po/LINGUAS)
LINGUAS ?= $(AVAILABLE_LANGUAGES)
PO_FILES := $(addprefix po/,$(addsuffix .po,$(LINGUAS)))
MO_FILES := $(PO_FILES:.po=.gmo)

DIST_NAME := $(PACKAGE)-$(VERSION)
DIST_ROOT := build/dist
DIST_DIR := $(DIST_ROOT)/$(DIST_NAME)

.DEFAULT_GOAL := all

.PHONY: all install uninstall clean distclean check check-version check-db \
	dist distdir dist-gzip dist-bzip2 dist-xz update-po

all: db/options.xml $(MO_FILES)

db/options.xml: db/options.xml.in VERSION
	@set -e; tmp="$@.tmp"; \
	awk -v version="$(VERSION)" 'NR == 1 { print; print "<!---Do not edit this file, edit options.xml.in instead.-->"; next } { gsub(/\$$DATE/, version); print }' "$<" > "$$tmp"; \
	mv "$$tmp" "$@"

po/%.gmo: po/%.po
	$(MSGFMT) --check -o "$@" "$<"

install: all
	$(MKDIR_P) "$(DESTDIR)$(DBDIR)/monitor"
	$(INSTALL_DATA) db/options.xml "$(DESTDIR)$(DBDIR)/options.xml"
	$(INSTALL_DATA) db/monitor/*.xml "$(DESTDIR)$(DBDIR)/monitor/"
	@set -e; for lang in $(LINGUAS); do \
		dir="$(DESTDIR)$(LOCALEDIR)/$$lang/LC_MESSAGES"; \
		$(MKDIR_P) "$$dir"; \
		$(INSTALL_DATA) "po/$$lang.gmo" "$$dir/$(PACKAGE).mo"; \
	done

uninstall:
	rm -f "$(DESTDIR)$(DBDIR)/options.xml"
	@for file in db/monitor/*.xml; do \
		rm -f "$(DESTDIR)$(DBDIR)/monitor/$${file##*/}"; \
	done
	@for lang in $(LINGUAS); do \
		rm -f "$(DESTDIR)$(LOCALEDIR)/$$lang/LC_MESSAGES/$(PACKAGE).mo"; \
	done
	-rmdir "$(DESTDIR)$(DBDIR)/monitor" "$(DESTDIR)$(DBDIR)" 2>/dev/null

check: all check-version

check-version:
	@case "$(VERSION)" in \
		[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) ;; \
		*) echo "VERSION must use YYYYMMDD format, got '$(VERSION)'" >&2; exit 1 ;; \
	esac
	@grep -q '<options date="$(VERSION)" dbversion="3">' db/options.xml || { \
		echo "db/options.xml does not contain version $(VERSION)" >&2; exit 1; \
	}

check-db: db/options.xml
	@command -v "$(DDCCONTROL)" >/dev/null 2>&1 || { \
		echo "$(DDCCONTROL) is required for make check-db" >&2; exit 1; \
	}
	@set -e; for file in db/monitor/*.xml; do \
		if ! grep -q NOCHECKDB "$$file"; then \
			name=$${file##*/}; name=$${name%.xml}; \
			$(DDCCONTROL) -b db -v -v -i "$$name"; \
		fi; \
	done

db/options.xml.h: db/options.xml xml2h.pl
	$(PERL) xml2h.pl db/options.xml

update-po: db/options.xml.h
	$(XGETTEXT) --from-code=UTF-8 --keyword=_ --keyword=N_ \
		--package-name="$(PACKAGE)" --package-version="$(VERSION)" \
		--msgid-bugs-address="ddccontrol-devel@lists.sourceforge.net" \
		-o po/$(PACKAGE).pot db/options.xml.h
	@set -e; for po in $(PO_FILES); do \
		$(MSGMERGE) --update --backup=none "$$po" po/$(PACKAGE).pot; \
	done

distdir: all
	rm -rf "$(DIST_ROOT)"
	$(MKDIR_P) "$(DIST_DIR)"
	@git ls-files --cached | \
		while IFS= read -r file; do test ! -e "$$file" || printf '%s\n' "$$file"; done \
		> build/dist-files
	COPYFILE_DISABLE=1 tar -cf - -T build/dist-files | COPYFILE_DISABLE=1 tar -xf - -C "$(DIST_DIR)"
	$(INSTALL_DATA) db/options.xml "$(DIST_DIR)/db/options.xml"
	$(INSTALL_DATA) $(MO_FILES) "$(DIST_DIR)/po/"

dist-gzip: distdir
	COPYFILE_DISABLE=1 tar -C "$(DIST_ROOT)" -czf "$(CURDIR)/$(DIST_NAME).tar.gz" "$(DIST_NAME)"

dist-bzip2: distdir
	COPYFILE_DISABLE=1 tar -C "$(DIST_ROOT)" -cjf "$(CURDIR)/$(DIST_NAME).tar.bz2" "$(DIST_NAME)"

dist-xz: distdir
	COPYFILE_DISABLE=1 tar -C "$(DIST_ROOT)" -cJf "$(CURDIR)/$(DIST_NAME).tar.xz" "$(DIST_NAME)"

dist: dist-gzip dist-bzip2 dist-xz

clean:
	rm -f db/options.xml db/options.xml.h po/*.gmo po/$(PACKAGE).pot
	rm -rf build

distclean: clean
	rm -f config.mk
	rm -f $(PACKAGE)-*.tar.gz $(PACKAGE)-*.tar.bz2 $(PACKAGE)-*.tar.xz
